
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action Action;

	private global::Gtk.Action Action1;

	private global::Gtk.Action Action2;

	private global::Gtk.Action Action5;

	private global::Gtk.Action Action4;

	private global::Gtk.Action Action18;

	private global::Gtk.Action Action7;

	private global::Gtk.Action Action8;

	private global::Gtk.Action Action12;

	private global::Gtk.Action Action10;

	private global::Gtk.Action Action11;

	private global::Gtk.Action Action13;

	private global::Gtk.Action Action14;

	private global::Gtk.Action Action15;

	private global::Gtk.Action Action16;

	private global::Gtk.Action SO2Action;

	private global::Gtk.Action Action17;

	private global::Gtk.Action HCIAction;

	private global::Gtk.VBox Manu;

	private global::Gtk.VBox vbox4;

	private global::Gtk.HSeparator hseparator5;

	private global::Gtk.HBox Menu;

	private global::Gtk.Button AddButton;

	private global::Gtk.Button Delete;

	private global::Gtk.HBox Search;

	private global::Gtk.Entry IDEntry;

	private global::Gtk.Button Redact;

	private global::Gtk.HSeparator hseparator3;

	private global::Gtk.HBox hbox1;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Entry id;

	private global::Gtk.Entry entry3;

	private global::Gtk.Entry entry5;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Entry entry7;

	private global::Gtk.Entry entry9;

	private global::Gtk.Entry entry11;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Entry entry13;

	private global::Gtk.Entry entry15;

	private global::Gtk.HBox hbox9;

	private global::Gtk.Entry entry17;

	private global::Gtk.Entry entry19;

	private global::Gtk.Label Text;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.Action = new global::Gtk.Action("Action", global::Mono.Unix.Catalog.GetString("Всі"), null, null);
		this.Action.ShortLabel = global::Mono.Unix.Catalog.GetString("Місто");
		w1.Add(this.Action, null);
		this.Action1 = new global::Gtk.Action("Action1", null, null, null);
		w1.Add(this.Action1, null);
		this.Action2 = new global::Gtk.Action("Action2", global::Mono.Unix.Catalog.GetString("Область"), null, null);
		this.Action2.ShortLabel = global::Mono.Unix.Catalog.GetString("Область");
		w1.Add(this.Action2, null);
		this.Action5 = new global::Gtk.Action("Action5", global::Mono.Unix.Catalog.GetString("Місто"), null, null);
		this.Action5.ShortLabel = global::Mono.Unix.Catalog.GetString("Місто");
		w1.Add(this.Action5, null);
		this.Action4 = new global::Gtk.Action("Action4", null, null, null);
		w1.Add(this.Action4, null);
		this.Action18 = new global::Gtk.Action("Action18", global::Mono.Unix.Catalog.GetString("Вибір по чому шукати"), null, null);
		this.Action18.ShortLabel = global::Mono.Unix.Catalog.GetString("Вибір по чому шукати");
		w1.Add(this.Action18, null);
		this.Action7 = new global::Gtk.Action("Action7", global::Mono.Unix.Catalog.GetString("Все"), null, null);
		this.Action7.ShortLabel = global::Mono.Unix.Catalog.GetString("Все");
		w1.Add(this.Action7, null);
		this.Action8 = new global::Gtk.Action("Action8", global::Mono.Unix.Catalog.GetString("Область"), null, null);
		this.Action8.ShortLabel = global::Mono.Unix.Catalog.GetString("Область");
		w1.Add(this.Action8, null);
		this.Action12 = new global::Gtk.Action("Action12", global::Mono.Unix.Catalog.GetString("Населений пункт"), null, null);
		this.Action12.ShortLabel = global::Mono.Unix.Catalog.GetString("Населений пункт");
		w1.Add(this.Action12, null);
		this.Action10 = new global::Gtk.Action("Action10", global::Mono.Unix.Catalog.GetString("Код Області"), null, null);
		this.Action10.ShortLabel = global::Mono.Unix.Catalog.GetString("Код Області");
		w1.Add(this.Action10, null);
		this.Action11 = new global::Gtk.Action("Action11", global::Mono.Unix.Catalog.GetString("Код Населеного пункту"), null, null);
		this.Action11.ShortLabel = global::Mono.Unix.Catalog.GetString("Код Населеного пункту");
		w1.Add(this.Action11, null);
		this.Action13 = new global::Gtk.Action("Action13", global::Mono.Unix.Catalog.GetString("Геморфологічна прив\'язка місця відбору проби"), null, null);
		this.Action13.ShortLabel = global::Mono.Unix.Catalog.GetString("Геморфологічна прив\'язка місця відбору проби");
		w1.Add(this.Action13, null);
		this.Action14 = new global::Gtk.Action("Action14", global::Mono.Unix.Catalog.GetString("дата відбору (Д/М/Р)"), null, null);
		this.Action14.ShortLabel = global::Mono.Unix.Catalog.GetString("дата відбору (Д/М/Р)");
		w1.Add(this.Action14, null);
		this.Action15 = new global::Gtk.Action("Action15", global::Mono.Unix.Catalog.GetString("Вуглекислий газ"), null, null);
		this.Action15.ShortLabel = global::Mono.Unix.Catalog.GetString("Вуглекислий газ");
		w1.Add(this.Action15, null);
		this.Action16 = new global::Gtk.Action("Action16", global::Mono.Unix.Catalog.GetString("СО"), null, null);
		this.Action16.ShortLabel = global::Mono.Unix.Catalog.GetString("СО");
		w1.Add(this.Action16, null);
		this.SO2Action = new global::Gtk.Action("SO2Action", global::Mono.Unix.Catalog.GetString(" SO2"), null, null);
		this.SO2Action.ShortLabel = global::Mono.Unix.Catalog.GetString(" SO2");
		w1.Add(this.SO2Action, null);
		this.Action17 = new global::Gtk.Action("Action17", global::Mono.Unix.Catalog.GetString("Бензин"), null, null);
		this.Action17.ShortLabel = global::Mono.Unix.Catalog.GetString("Бензин");
		w1.Add(this.Action17, null);
		this.HCIAction = new global::Gtk.Action("HCIAction", global::Mono.Unix.Catalog.GetString("HCI"), null, null);
		this.HCIAction.ShortLabel = global::Mono.Unix.Catalog.GetString("HCI");
		w1.Add(this.HCIAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.Manu = new global::Gtk.VBox();
		this.Manu.Name = "Manu";
		this.Manu.Spacing = 6;
		// Container child Manu.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hseparator5 = new global::Gtk.HSeparator();
		this.hseparator5.Name = "hseparator5";
		this.vbox4.Add(this.hseparator5);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hseparator5]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.Menu = new global::Gtk.HBox();
		this.Menu.Name = "Menu";
		this.Menu.Spacing = 6;
		// Container child Menu.Gtk.Box+BoxChild
		this.AddButton = new global::Gtk.Button();
		this.AddButton.CanFocus = true;
		this.AddButton.Name = "AddButton";
		this.AddButton.UseUnderline = true;
		this.AddButton.Label = global::Mono.Unix.Catalog.GetString("Добавити");
		this.Menu.Add(this.AddButton);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.Menu[this.AddButton]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child Menu.Gtk.Box+BoxChild
		this.Delete = new global::Gtk.Button();
		this.Delete.CanFocus = true;
		this.Delete.Name = "Delete";
		this.Delete.UseUnderline = true;
		this.Delete.Label = global::Mono.Unix.Catalog.GetString("Видалити");
		this.Menu.Add(this.Delete);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.Menu[this.Delete]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child Menu.Gtk.Box+BoxChild
		this.Search = new global::Gtk.HBox();
		this.Search.Name = "Search";
		this.Search.Spacing = 6;
		// Container child Search.Gtk.Box+BoxChild
		this.IDEntry = new global::Gtk.Entry();
		this.IDEntry.CanFocus = true;
		this.IDEntry.Name = "IDEntry";
		this.IDEntry.IsEditable = true;
		this.IDEntry.InvisibleChar = '●';
		this.Search.Add(this.IDEntry);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.Search[this.IDEntry]));
		w5.Position = 0;
		// Container child Search.Gtk.Box+BoxChild
		this.Redact = new global::Gtk.Button();
		this.Redact.CanFocus = true;
		this.Redact.Name = "Redact";
		this.Redact.UseUnderline = true;
		this.Redact.Label = global::Mono.Unix.Catalog.GetString(" Редагувати");
		this.Search.Add(this.Redact);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.Search[this.Redact]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		this.Menu.Add(this.Search);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.Menu[this.Search]));
		w7.Position = 2;
		this.vbox4.Add(this.Menu);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.Menu]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hseparator3 = new global::Gtk.HSeparator();
		this.hseparator3.Name = "hseparator3";
		this.vbox4.Add(this.hseparator3);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hseparator3]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		this.Manu.Add(this.vbox4);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.Manu[this.vbox4]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child Manu.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.id = new global::Gtk.Entry();
		this.id.CanFocus = true;
		this.id.Name = "id";
		this.id.IsEditable = true;
		this.id.InvisibleChar = '●';
		this.hbox7.Add(this.id);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.id]));
		w11.Position = 0;
		// Container child hbox7.Gtk.Box+BoxChild
		this.entry3 = new global::Gtk.Entry();
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.IsEditable = true;
		this.entry3.InvisibleChar = '●';
		this.hbox7.Add(this.entry3);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.entry3]));
		w12.Position = 1;
		// Container child hbox7.Gtk.Box+BoxChild
		this.entry5 = new global::Gtk.Entry();
		this.entry5.CanFocus = true;
		this.entry5.Name = "entry5";
		this.entry5.IsEditable = true;
		this.entry5.InvisibleChar = '●';
		this.hbox7.Add(this.entry5);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.entry5]));
		w13.Position = 2;
		this.hbox1.Add(this.hbox7);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hbox7]));
		w14.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.entry7 = new global::Gtk.Entry();
		this.entry7.CanFocus = true;
		this.entry7.Name = "entry7";
		this.entry7.IsEditable = true;
		this.entry7.InvisibleChar = '●';
		this.hbox3.Add(this.entry7);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.entry7]));
		w15.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.entry9 = new global::Gtk.Entry();
		this.entry9.CanFocus = true;
		this.entry9.Name = "entry9";
		this.entry9.IsEditable = true;
		this.entry9.InvisibleChar = '●';
		this.hbox3.Add(this.entry9);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.entry9]));
		w16.Position = 1;
		// Container child hbox3.Gtk.Box+BoxChild
		this.entry11 = new global::Gtk.Entry();
		this.entry11.CanFocus = true;
		this.entry11.Name = "entry11";
		this.entry11.IsEditable = true;
		this.entry11.InvisibleChar = '●';
		this.hbox3.Add(this.entry11);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.entry11]));
		w17.Position = 2;
		this.hbox1.Add(this.hbox3);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hbox3]));
		w18.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.entry13 = new global::Gtk.Entry();
		this.entry13.CanFocus = true;
		this.entry13.Name = "entry13";
		this.entry13.IsEditable = true;
		this.entry13.InvisibleChar = '●';
		this.hbox5.Add(this.entry13);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.entry13]));
		w19.Position = 0;
		// Container child hbox5.Gtk.Box+BoxChild
		this.entry15 = new global::Gtk.Entry();
		this.entry15.CanFocus = true;
		this.entry15.Name = "entry15";
		this.entry15.IsEditable = true;
		this.entry15.InvisibleChar = '●';
		this.hbox5.Add(this.entry15);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.entry15]));
		w20.Position = 1;
		// Container child hbox5.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.entry17 = new global::Gtk.Entry();
		this.entry17.CanFocus = true;
		this.entry17.Name = "entry17";
		this.entry17.IsEditable = true;
		this.entry17.InvisibleChar = '●';
		this.hbox9.Add(this.entry17);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.entry17]));
		w21.Position = 0;
		// Container child hbox9.Gtk.Box+BoxChild
		this.entry19 = new global::Gtk.Entry();
		this.entry19.CanFocus = true;
		this.entry19.Name = "entry19";
		this.entry19.IsEditable = true;
		this.entry19.InvisibleChar = '●';
		this.hbox9.Add(this.entry19);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.entry19]));
		w22.Position = 1;
		this.hbox5.Add(this.hbox9);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.hbox9]));
		w23.Position = 2;
		this.hbox1.Add(this.hbox5);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hbox5]));
		w24.Position = 2;
		this.Manu.Add(this.hbox1);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.Manu[this.hbox1]));
		w25.Position = 1;
		w25.Expand = false;
		w25.Fill = false;
		// Container child Manu.Gtk.Box+BoxChild
		this.Text = new global::Gtk.Label();
		this.Text.Name = "Text";
		this.Text.LabelProp = global::Mono.Unix.Catalog.GetString("label1");
		this.Manu.Add(this.Text);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.Manu[this.Text]));
		w26.Position = 2;
		w26.Expand = false;
		w26.Fill = false;
		this.Add(this.Manu);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 1690;
		this.DefaultHeight = 617;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.AddButton.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler(this.OnAddButtonButtonPressEvent);
		this.Delete.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler(this.OnDeleteButtonPressEvent);
	}
}
